name: rdx_manu_web
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # get: ^4.3.8
  get_it: ^7.2.0
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  url_strategy: ^0.2.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  brasil_fields: ^1.1.4
  flutter_masked_text2: ^0.9.1
  csv_picker_button: ^0.0.7
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  flutter_sound: ^8.2.0
  auto_size_text: ^3.0.0-nullsafety.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0  


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/icons/home.svg
    - assets/icons/add.svg
    - assets/icons/lists.svg
    - assets/icons/account.svg
    - assets/icons/logo.svg
    - assets/icons/approver.svg
    - assets/icons/cliente.svg
    - assets/icons/fork_lift.svg
    - assets/icons/mecanico.svg
    - assets/icons/os.svg
    - assets/icons/peca.svg
    - assets/icons/requester.svg
    - assets/icons/unidade.svg
    - assets/login.png
    - assets/manu_home.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
